version: "3.5"

services:
  postgres:
    image: "postgres:latest"
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"

  web:
    build:
      context: ../
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ../:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - ../.env

volumes:
  db_data:
